/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "led.h"
#include "uart.h"
#include "oskernel.h"

#define QUANTA           10

typedef uint32_t TaskProfiler;
TaskProfiler Task0_Profiler;
TaskProfiler Task1_Profiler;
TaskProfiler Task2_Profiler;

void motor_run();
void motor_stop();
void valve_open();
void valve_close();

/*user defined threads*/
void task0(void){
	while(1){
		Task0_Profiler++;

	}
}

void task1(void){
	while(1){
		Task1_Profiler++;

	}
}

void task2(void){
	while(1){
		Task2_Profiler++;

	}
}
void (*threads[NUM_OF_THREADS])(void); /*threads array*/

int main(void){
	threads[0] = task0;
	threads[1] = task1;
	threads[2] = task2;
	/*Initialize the kernel*/
	osKernelInit();

	/*add threads*/
	osKernelAddThreads(threads);

	/*set RR time quanta*/
	osKernelLaunch(QUANTA);
}
void motor_run(void){
	printf("motor is starting...\n\r");
}
void motor_stop(void){
	printf("motor is stopping...\n\r");
}

void valve_open(void){
	printf("valve is opening...\n\r");
}
void valve_close(void){
	printf("valve is closing...\n\r");
}



