/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "led.h"
#include "uart.h"
#include "oskernel.h"
#include "gpio_driver.h"

#define QUANTA           1

typedef uint32_t TaskProfiler;
TaskProfiler Task0_Profiler;
TaskProfiler Task1_Profiler;
TaskProfiler Task2_Profiler;
TaskProfiler Task3_Profiler;
TaskProfiler Idle_Profiler;


/*user defined threads*/
void idle(void){
	while(1){
		 Idle_Profiler++;

	}
}
void task0(void){
	while(1){
		Task0_Profiler++;
		GPIO_TogglePin(GPIOD, GPIO_PIN_12);
		thread_delay(1000);

	}
}

void task1(void){
	while(1){
		Task1_Profiler++;
		GPIO_TogglePin(GPIOD, GPIO_PIN_13);
		thread_delay(500);

	}
}

void task2(void){
	while(1){
		Task2_Profiler++;
		GPIO_TogglePin(GPIOD, GPIO_PIN_14);
		thread_delay(250);

	}
}


void task3(void){
	while(1){
		Task3_Profiler++;
		GPIO_TogglePin(GPIOD, GPIO_PIN_15);
		thread_delay(125);

	}
}
void (*threads[NUM_OF_THREADS])(void); /*threads array*/

int main(void){
	threads[0] = idle;
	threads[1] = task0;
	threads[2] = task1;
	threads[3] = task2;
	threads[4] = task3;
	/*Initialize the kernel*/
	led_init();
	osKernelInit();

	/*add threads*/
	osKernelAddThreads(threads);

	/*set RR time quanta*/
	osKernelLaunch(QUANTA);
}



